### ISSUE TITLE
Send Email for Deliverable B

### ISSUE THREAD

**Issue by Ashwing101** [thefueley/sus#62]
Activity for #50 

Once we finished creating a binary tree for each team member individually submit the resulting diagram in Graphviz format. Additionally, submit the spreadsheet containing the individual user story priority list and send an email to the professor as part of Deliverable B.

**Comment by thefueley** [comment]
Working copy of Deliverable B.

[Team_4_Bigraph.txt](https://github.com/thefueley/sus/files/13323927/Team_4_Bigraph.txt)

**Comment by Kartikeychugh** [comment]
[Updated] Working copy of Deliverable B.



[Team_4_Bigraph.txt](https://github.com/thefueley/sus/files/13343186/Team_4_Bigraph.txt)

**Comment by Kartikeychugh** [comment]
[All team member's digraph] 

[Team_4_Bigraph.txt](https://github.com/thefueley/sus/files/13358332/Team_4_Bigraph.txt)

**Comment by VodkaBottle** [comment]
Email sent!
