### ISSUE TITLE
Resolve improperly created user stories

### ISSUE THREAD

**Issue by VodkaBottle** [thefueley/sus#64]
Activity for Epic #12

- [x] Migrate re-worded user stories from Github issue format to spreadsheet
- [x] Close all user story issues

**Comment by VodkaBottle** [comment]
User Stories Spreadsheet: https://docs.google.com/spreadsheets/d/12xpFrnLqsc_ehur8PvO4iCOg49Jr2Hq4wFtzj1nfTeQ/edit#gid=0

Let me know what you think, and approve once you think its ready for the next steps.

- [ ] @thefueley 
- [ ] @Ashwing101 
- [ ] @Kartikeychugh

**Comment by thefueley** [comment]
Good here.
