### ISSUE TITLE
Send Email for Deliverable C

### ISSUE THREAD

**Issue by Ashwing101** [thefueley/sus#73]
Activity for #62 

Execute the creation of individual binary graphs, followed by the amalgamation of these graphs into a singular entity using the Graphviz format. Subsequently, initiate the process of sending an email to the professor to communicate the accomplishment of Deliverable C.

**Comment by thefueley** [comment]
Adding working file for Deliverable C. @Ashwing101, can you compile and send the final list?
[Team_4_UserStories.xlsx](https://github.com/thefueley/sus/files/13353799/Team_4_UserStories.xlsx)

**Comment by Kartikeychugh** [comment]
Merged priorities.

[Team_4_UserStories.xlsx](https://github.com/thefueley/sus/files/13358336/Team_4_UserStories.xlsx)

**Comment by thefueley** [comment]
Looks like we're ready to send Deliverable C. Agree all? @Kartikeychugh  @Ashwing101 @VodkaBottle

**Comment by VodkaBottle** [comment]
> Looks like we're ready to send Deliverable C. Agree all? @Kartikeychugh @Ashwing101 @VodkaBottle

Looks good to me!

**Comment by VodkaBottle** [comment]
Email sent!
